@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueClientList
AddressBook *-right-> "1" UniquePolicyList
UniquePolicyList -[hidden]down- UniqueClientList
UniquePolicyList -[hidden]down- UniqueClientList

UniqueClientList -right-> Client
UniquePolicyList *-right-> "~*" Policy

Client *--> Name
Client *--> Phone
Client *--> Email
Client *--> Address
Client *--> Birthday
Client *--> LastContacted
Client *-up-> "1" UniquePolicyList
Client *--> PreferenceMap
Client *--> Note
@enduml
